"use client";
import {useEffect,useMemo,useState} from "react";
import {Bike,Check,ChevronDown,Clock3,Copy,MapPin,Minus,Navigation,Phone,Plus,ShoppingBag,Store,Trash2,Utensils,X} from "lucide-react";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger} from "@/components/ui/sheet";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Label} from "@/components/ui/label";

type Item={id:string;name:string;description:string;price:number;image:string}; type Line=Item&{qty:number;note:string}; type OT="Delivery"|"Pickup"|"Dine-In"; type Status="Order Received"|"Confirmed"|"Preparing"|"Ready for Delivery"|"Driver Assigned"|"On Delivery"|"Arriving"|"Delivered"|"Rejected";
type Order={number:string;customer:string;phone:string;type:OT;address:string;location:string;table:string;requestedTime:string;notes:string;deliveryFee:number;items:Line[];subtotal:number;total:number;status:Status;driver:string;createdAt:string};
const menu:Item[]=[
 {id:"single",name:"Single Set Meal",description:"Ramen with Side Dishes",price:9.9,image:"./single-set.jpg"},
 {id:"double",name:"Double Set Meal",description:"Sushi Set with Miso Soup",price:28.8,image:"./double-set.jpg"},
 {id:"three",name:"Three Set Meal",description:"Sashimi, Fried Food, and Main Course",price:58.8,image:"./three-set.jpg"},
 {id:"four",name:"Four Set Meal",description:"Grilled Skewers Platter",price:88.8,image:"./four-set.jpg"}];
const individualMenuCounts:Record<number,number>={28:6,29:6,46:5,47:4,48:4,49:4,51:5,52:5,53:5,62:6,64:5,65:6,67:3,68:7,69:6,71:7,72:7,73:6,74:4,75:4,77:6,78:1,79:2};
const categoryForPage=(page:number)=>page<=29?"Appetizers":page<=49?"Sushi Rolls":page<=53?"Nigiri & Sushi":page<=65?"Rice & Noodles":page<=73?"Sides & Fried":page<=75?"Desserts":"Drinks";
const individualMenu=Object.entries(individualMenuCounts).flatMap(([page,count])=>Array.from({length:count},(_,index)=>({
 id:`p${page}-${index+1}`,
 page:Number(page),
 category:categoryForPage(Number(page)),
 image:`./assets/images/items/page-${String(page).padStart(2,"0")}-item-${String(index+1).padStart(2,"0")}.png`
})));
const individualCategories=["All",...Array.from(new Set(individualMenu.map(item=>item.category)))];
const statuses:Status[]=["Order Received","Confirmed","Preparing","Ready for Delivery","Driver Assigned","On Delivery","Arriving","Delivered"];
const money=(n:number)=>`$${n.toFixed(2)}`; const blank={customer:"",phone:"",type:"Delivery" as OT,address:"",location:"",table:"",requestedTime:"",notes:"",deliveryFee:"0.00"};
function message(o:Order){const lines=o.items.flatMap(i=>[`${i.qty}x ${i.name}`,`${money(i.price)} × ${i.qty} = ${money(i.price*i.qty)}`,...(i.note?[`Item note: ${i.note}`]:[]),""]);return ["🍣 NEW ORDER — 小仙女","",`Order No: #${o.number}`,"","Customer:",o.customer,"","Phone:",o.phone,"","Order Type:",o.type,"",...(o.type==="Delivery"?["ADDRESS:",o.address,"","LOCATION:",o.location||"Not provided",""]:[]),...(o.type==="Dine-In"?["TABLE:",o.table,""]:[]),...(o.requestedTime?["REQUESTED TIME:",o.requestedTime,""]:[]),"ORDER:","",...lines,"--------------------","",`Subtotal: ${money(o.subtotal)}`,`Delivery Fee: ${money(o.deliveryFee)}`,`TOTAL: ${money(o.total)}`,"","NOTES:",o.notes||"None","","Please confirm this order.","Thank you."].join("\n")}
function Qty({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="qty"><button type="button" aria-label="Decrease quantity" onClick={()=>onChange(Math.max(0,value-1))}><Minus size={15}/></button><span>{value}</span><button type="button" aria-label="Increase quantity" onClick={()=>onChange(value+1)}><Plus size={15}/></button></div>}

export default function Home(){
 const[cart,setCart]=useState<Line[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[form,setForm]=useState(blank),[orders,setOrders]=useState<Order[]>([]),[active,setActive]=useState<Order|null>(null),[notice,setNotice]=useState(""),[view,setView]=useState("menu"),[menuCategory,setMenuCategory]=useState("All");
 useEffect(()=>{const raw=localStorage.getItem("xx-orders");const saved:Order[]=raw?JSON.parse(raw):[];setOrders(saved);const q=new URLSearchParams(location.search),v=q.get("view"),n=q.get("order");if(v)setView(v);if(n)setActive(saved.find(o=>o.number===n)||null)},[]);
 const persist=(next:Order[])=>{setOrders(next);localStorage.setItem("xx-orders",JSON.stringify(next))}; const count=cart.reduce((s,i)=>s+i.qty,0),subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0),fee=form.type==="Delivery"?Math.max(0,Number(form.deliveryFee)||0):0,total=subtotal+fee;
 const qty=(item:Item,n:number)=>setCart(c=>n===0?c.filter(x=>x.id!==item.id):c.some(x=>x.id===item.id)?c.map(x=>x.id===item.id?{...x,qty:n}:x):[...c,{...item,qty:n,note:""}]);
 const add=(item:Item)=>{qty(item,(cart.find(x=>x.id===item.id)?.qty||0)+1);setNotice(`${item.name} added to cart`);setTimeout(()=>setNotice(""),1800)};
 const change=(number:string,c:Partial<Order>)=>{const next=orders.map(o=>o.number===number?{...o,...c}:o);persist(next);if(active?.number===number)setActive({...active,...c})};
 const go=(v:string,o=active)=>{setView(v);history.replaceState(null,"",v==="menu"?location.pathname:`?view=${v}${o?`&order=${o.number}`:""}`)};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!cart.length)return;const number=`XX${String(Date.now()).slice(-6)}`;const o:Order={number,...form,deliveryFee:fee,items:cart,subtotal,total,status:"Order Received",driver:"Unassigned",createdAt:new Date().toISOString()};persist([o,...orders]);setActive(o);setCart([]);setCheckout(false);setCartOpen(false);go("track",o);setNotice("Order created. Choose a contact method to send it.")};
 const send=async(c:"WhatsApp"|"Telegram")=>{if(!active)return;await navigator.clipboard.writeText(message(active));setNotice(c==="Telegram"?"Order copied. Paste the message and tap Send.":"Order copied. Admin WhatsApp number is not configured yet.")};
 return <main>{notice&&<div className="toast"><Check size={17}/>{notice}</div>}
  <header className="topbar"><a className="brand" href="#top"><span>小仙女</span><small>JAPANESE CUISINE</small></a><nav>{["menu","track","driver","admin"].map(v=><button key={v} onClick={()=>go(v)}>{v}</button>)}</nav><Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetTrigger asChild><button className="cart-button"><ShoppingBag size={18}/><span>Cart</span><b>{count}</b></button></SheetTrigger><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Your order</SheetTitle></SheetHeader><Cart cart={cart} qty={qty} note={(id,note)=>setCart(cart.map(x=>x.id===id?{...x,note}:x))} subtotal={subtotal} checkout={()=>setCheckout(true)}/></SheetContent></Sheet></header>
  <Tabs value={view} onValueChange={go}><TabsList className="mobile-tabs"><TabsTrigger value="menu"><Utensils/>Menu</TabsTrigger><TabsTrigger value="track"><MapPin/>Track</TabsTrigger><TabsTrigger value="driver"><Bike/>Driver</TabsTrigger><TabsTrigger value="admin"><Store/>Admin</TabsTrigger></TabsList>
   <TabsContent value="menu"><section id="top" className="hero"><img src="./hero-sushi.jpg" alt="Japanese dishes prepared by Xiao Xiannu Japanese Restaurant"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">小仙女日式料理</p><h1>小仙女 <i>Japanese</i><br/>Restaurant</h1><p>Japanese Cuisine</p><div className="service-line"><span><Clock3/>Open 24 Hours</span><span>Dine-In • Pickup • Delivery</span></div><div className="hero-actions"><a href="#menu">Order Now</a><a className="ghost" href="#menu">View Menu <ChevronDown/></a></div></div></section>
   <section id="menu" className="menu-section"><div className="section-heading"><div><p className="eyebrow red">ORDERING DEMO</p><h2>Featured Set Meals</h2></div><p>These four confirmed selections demonstrate the cart and checkout flow. Browse the complete original restaurant menu below.</p></div><div className="menu-grid">{menu.map(item=>{const n=cart.find(x=>x.id===item.id)?.qty||0;return <article className="menu-card" key={item.id}><div className="photo"><img src={item.image} alt={item.name}/><span>SET MEAL</span></div><div className="card-copy"><div><h3>{item.name}</h3><p>{item.description}</p></div><strong>{money(item.price)}</strong><div className="card-actions">{n?<Qty value={n} onChange={v=>qty(item,v)}/>:<span className="fresh">Made to order</span>}<button onClick={()=>add(item)}><Plus size={17}/> Add to Cart</button></div></div></article>})}</div></section>
   <section className="full-menu-section"><div className="section-heading"><div><p className="eyebrow red">INDIVIDUAL MENU GALLERY</p><h2>Explore Every Dish</h2></div><p>114 original food images have been separated for clearer mobile viewing. Tap a dish to see the full-quality image.</p></div><div className="menu-category-tabs" role="tablist" aria-label="Menu categories">{individualCategories.map(category=><button className={menuCategory===category?"active":""} key={category} onClick={()=>setMenuCategory(category)}>{category}</button>)}</div><div className="individual-menu-grid">{individualMenu.filter(item=>menuCategory==="All"||item.category===menuCategory).map(item=><a className="individual-menu-item" href={item.image} target="_blank" rel="noreferrer" key={item.id}><img src={item.image} loading="lazy" alt={`${item.category} menu item ${item.id}`}/><span><b>{item.category}</b><small>Reference {item.id.toUpperCase()}</small></span></a>)}</div></section>
   <section className="demo-note"><div><p className="eyebrow red">DELIVERY PRO DEMO</p><h2>A complete ordering journey.</h2></div><div className="feature-grid"><span><b>Real demo</b>Menu, cart, totals, customer form, and order-message handoff.</span><span><b>Simulated demo</b>Driver movement, live GPS, backend sync, and multi-device tracking.</span></div></section></TabsContent>
   <TabsContent value="track"><Tracking order={active||orders[0]} copy={async()=>{if(active){await navigator.clipboard.writeText(`${location.origin}${location.pathname}?view=track&order=${active.number}`);setNotice("Tracking link copied.")}}} send={send}/></TabsContent>
   <TabsContent value="driver"><Driver orders={orders} change={change}/></TabsContent><TabsContent value="admin"><Admin orders={orders} change={change} track={o=>{setActive(o);go("track",o)}}/></TabsContent>
  </Tabs>
  {checkout&&<div className="modal-backdrop" role="dialog" aria-modal="true"><form className="checkout" onSubmit={submit}><div className="modal-title"><div><p className="eyebrow red">CHECKOUT</p><h2>Complete your order</h2></div><button type="button" aria-label="Close" onClick={()=>setCheckout(false)}><X/></button></div><div className="form-grid"><label>Customer Name<input required value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label>Phone Number<input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><fieldset><legend>Order Type</legend><RadioGroup className="type-grid" value={form.type} onValueChange={v=>setForm({...form,type:v as OT})}>{["Delivery","Pickup","Dine-In"].map(t=><Label className="type-option" key={t}><RadioGroupItem value={t}/>{t}</Label>)}</RadioGroup></fieldset>{form.type==="Delivery"&&<><label>Delivery Address<textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Google Maps / Location Link<input type="url" placeholder="https://maps.google.com/..." value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Delivery Fee ($)<input min="0" step="0.01" type="number" value={form.deliveryFee} onChange={e=>setForm({...form,deliveryFee:e.target.value})}/></label></>}{form.type==="Dine-In"&&<label>Table Number<input required value={form.table} onChange={e=>setForm({...form,table:e.target.value})}/></label>}<label>Requested time <small>(optional)</small><input type="time" value={form.requestedTime} onChange={e=>setForm({...form,requestedTime:e.target.value})}/></label><label>Customer Notes <small>(optional)</small><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="checkout-total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary wide" type="submit">Generate Order</button></form></div>}
 </main>}

function Cart({cart,qty,note,subtotal,checkout}:{cart:Line[];qty:(i:Item,n:number)=>void;note:(id:string,n:string)=>void;subtotal:number;checkout:()=>void}){return <div className="cart-content">{!cart.length?<Empty title="Your cart is empty" text="Add a set meal to begin your order."/>:<>{cart.map(i=><article className="cart-line" key={i.id}><img src={i.image} alt=""/><div><h3>{i.name}</h3><span>{money(i.price)} each</span><textarea placeholder="Item note (optional)" value={i.note} onChange={e=>note(i.id,e.target.value)}/><div className="cart-row"><Qty value={i.qty} onChange={n=>qty(i,n)}/><strong>{money(i.price*i.qty)}</strong><button aria-label="Remove" onClick={()=>qty(i,0)}><Trash2 size={16}/></button></div></div></article>)}<div className="totals"><span>Subtotal <b>{money(subtotal)}</b></span><small>Delivery fee is entered at checkout.</small></div><button className="primary wide" onClick={checkout}>Continue to Checkout</button></>}</div>}
function Tracking({order,copy,send}:{order?:Order;copy:()=>void;send:(c:"WhatsApp"|"Telegram")=>void}){if(!order)return <Empty title="No order to track" text="Create an order from the menu to see its tracking page."/>;const index=Math.max(0,statuses.indexOf(order.status));return <section className="workspace"><div className="workspace-head"><div><p className="eyebrow red">CUSTOMER TRACKING</p><h1>Order #{order.number}</h1></div><button className="outline" onClick={copy}><Copy/>Copy tracking link</button></div><div className="tracking-grid"><article className="panel status-panel"><span className="status-pill">{order.status}</span><h2>{order.status==="Delivered"?"Your order has arrived.":"We’re taking care of your order."}</h2><p>Estimated arrival: <b>{["On Delivery","Arriving"].includes(order.status)?"Demo estimate: 20–30 min":"Awaiting restaurant update"}</b></p><div className="timeline">{statuses.map((s,i)=><div className={i<=index?"done":""} key={s}><i>{i<index?<Check/>:i+1}</i><span>{s}</span></div>)}</div></article><article className="panel map-panel"><div className="demo-badge">SIMULATED MAP — NOT LIVE GPS</div><div className="route-line"/><MapPin className="restaurant-pin"/><Bike className="driver-pin"/><Navigation className="destination-pin"/><div className="map-label start">Restaurant</div><div className="map-label end">Destination</div><div className="map-footer"><span><b>Driver</b>{order.driver}</span><span><b>Driver status</b>{["On Delivery","Arriving"].includes(order.status)?order.status:"Not active"}</span></div></article></div><article className="panel send-panel"><div><h2>Send complete order</h2><p>The full message is copied first. Admin contacts are awaiting configuration.</p></div><button onClick={()=>send("WhatsApp")}><Phone/>Copy for WhatsApp</button><button onClick={()=>send("Telegram")}><Navigation/>Copy for Telegram</button></article></section>}
function Driver({orders,change}:{orders:Order[];change:(n:string,c:Partial<Order>)=>void}){const active=orders.filter(o=>o.type==="Delivery"&&!['Delivered','Rejected'].includes(o.status));return <section className="workspace dark-workspace"><div className="workspace-head"><div><p className="eyebrow red">DRIVER MODE</p><h1>Delivery route</h1><p className="muted">Demo controls on this device. Production GPS requires a backend.</p></div><span className="route-count">{active.length} STOPS</span></div>{!active.length?<Empty title="No assigned deliveries" text="Delivery orders accepted by admin will appear here."/>:<div className="stops">{active.map((o,i)=><article className="stop" key={o.number}><span>STOP {i+1}</span><div><h2>{o.customer}</h2><p>Order #{o.number}</p><p>{o.address}</p></div><div className="stop-actions">{o.location&&<a href={o.location} target="_blank"><Navigation/>Open navigation</a>}<select value={o.status} onChange={e=>change(o.number,{status:e.target.value as Status})}>{statuses.slice(4).map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>change(o.number,{status:"Delivered"})}>Mark delivered</button></div></article>)}</div>}</section>}
function Admin({orders,change,track}:{orders:Order[];change:(n:string,c:Partial<Order>)=>void;track:(o:Order)=>void}){const counts=useMemo(()=>statuses.map(s=>({s,count:orders.filter(o=>o.status===s).length})),[orders]);return <section className="workspace"><div className="workspace-head"><div><p className="eyebrow red">ADMIN DASHBOARD</p><h1>Order operations</h1><p className="muted">Local demo data only — no real-time multi-device synchronization.</p></div></div><div className="stat-grid">{counts.filter(x=>["Order Received","Confirmed","Preparing","Ready for Delivery","On Delivery","Delivered"].includes(x.s)).map(x=><div key={x.s}><b>{x.count}</b><span>{x.s}</span></div>)}</div>{!orders.length?<Empty title="No orders yet" text="Complete a customer checkout to create the first demo order."/>:<div className="orders">{orders.map(o=><article className="order-card" key={o.number}><div className="order-top"><div><span>#{o.number}</span><h2>{o.customer}</h2><a href={`tel:${o.phone}`}><Phone/> {o.phone}</a></div><strong>{money(o.total)}</strong></div><p><b>{o.type}</b>{o.address?` · ${o.address}`:""}</p><ul>{o.items.map(i=><li key={i.id}>{i.qty}× {i.name} — {money(i.qty*i.price)}{i.note&&<small>Note: {i.note}</small>}</li>)}</ul>{o.notes&&<p className="order-note">Notes: {o.notes}</p>}<div className="admin-controls"><button onClick={()=>change(o.number,{status:"Confirmed"})}>Accept</button><button className="reject" onClick={()=>change(o.number,{status:"Rejected"})}>Reject</button><select value={o.status} onChange={e=>change(o.number,{status:e.target.value as Status})}>{[...statuses,"Rejected"].map(s=><option key={s}>{s}</option>)}</select><input placeholder="Assign driver" value={o.driver==="Unassigned"?"":o.driver} onChange={e=>change(o.number,{driver:e.target.value||"Unassigned",status:e.target.value?"Driver Assigned":o.status})}/>{o.location&&<a href={o.location} target="_blank"><MapPin/>Location</a>}<button className="outline" onClick={()=>track(o)}>View tracking</button></div></article>)}</div>}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-panel"><div><ShoppingBag/></div><h2>{title}</h2><p>{text}</p></div>}
