import {useMemo,useState} from "react";
import {ChevronLeft,ChevronRight,Search} from "lucide-react";
import type {CartLine,MenuItem} from "../../types/menu";
import {categories,menu} from "../../data/menu";
import {formatCurrency} from "../../lib/currency";

export function BookSpread({cart,onOpen,onQty}:{cart:CartLine[];onOpen:(item:MenuItem)=>void;onQty:(item:MenuItem,qty:number)=>void}){
 const[category,setCategory]=useState("Sashimi"),[query,setQuery]=useState("");
 const items=useMemo(()=>menu.filter(i=>(category==="All"||i.category===category)&&(!query||`${i.id} ${i.name} ${i.description}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
 const scroll=(dir:number)=>document.querySelector(".book-pages")?.scrollBy({left:dir*window.innerWidth*.78,behavior:"smooth"});
 return <section className="menu-book-screen"><div className="book-toolbar"><div><p>DIGITAL MENU BOOK</p><h1>Choose your dish</h1></div><label className="menu-search"><Search/><input placeholder="Search menu..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="category-pills"><button className={category==="All"?"active":""} onClick={()=>setCategory("All")}>All</button>{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="book-shell"><button className="book-arrow left" aria-label="Previous" onClick={()=>scroll(-1)}><ChevronLeft/></button><div className="book-pages">{items.map((item,index)=>{const qty=cart.find(x=>x.id===item.id)?.qty||0;return <article className="book-page" key={item.id} onClick={()=>onOpen(item)}><div className="page-number">PAGE {String(index+1).padStart(2,"0")}</div><div className="book-image"><img src={`${item.image}?v=20260830-book`} alt={item.name}/><span>{item.id}</span></div><div className="book-copy"><h2>{item.name}</h2><p>{item.description}</p><strong>{formatCurrency(item.price)} <small>{item.unit||""}</small></strong><div className="book-qty" onClick={e=>e.stopPropagation()}>{qty>0?<><button onClick={()=>onQty(item,Math.max(0,qty-1))}>−</button><b>{qty}</b><button onClick={()=>onQty(item,qty+1)}>+</button></>:<button className="add-mini" onClick={()=>onQty(item,1)}>ADD</button>}</div></div></article>})}</div><button className="book-arrow right" aria-label="Next" onClick={()=>scroll(1)}><ChevronRight/></button></div><p className="book-hint">Swipe left or right on mobile • Two-page menu on larger screens</p></section>}
